- alias: "Link config directories"
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: shell_command.ln_file
    data:
      src: /git/current/www
      dst: www
  - service: shell_command.ln_file
    data:
      src: /git/current/ui-lovelace.yaml
      dst: ui-lovelace.yaml
