homeassistant:
  auth_mfa_modules:
    - type: totp
#
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http: !include http.yaml

logger:
  default: info
  logs:
    homeassistant.components.shell_command: debug

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_commands.yaml
