title: Home
views:
  - path: default_view
    title: Home
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.forecast_home
        secondary_info_attribute: precipitation
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.forecast_home_hourly
        secondary_info_attribute: precipitation
      - type: "custom:sun-card"
        entity: sun.sun


