title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: vertical-stack
        cards:
        - show_current: true
          show_forecast: true
          type: weather-forecast
          entity: weather.forecast_home
          secondary_info_attribute: precipitation
        - show_current: false
          show_forecast: true
          type: weather-forecast
          entity: weather.forecast_home_hourly
          secondary_info_attribute: precipitation
        - type: "custom:sun-card"
          entity: sun.sun
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: sensor.mealie_todays_meal
          name: Dinner
          show_state: true
          show_name: true
          image: 'http://mealie.mealie:9000/api/meal-plans/today/image?group_name=Home'
        - type: media-control
          entity: media_player.sound_system


