title: Home
views:
  - path: default_view
    title: Overview
    cards:
      - type: vertical-stack
        cards:
        - show_current: true
          show_forecast: true
          secondary_info_attribute: humidity
          name: Home
          type: weather-forecast
          entity: weather.ksea_hourly
        - show_current: false
          show_forecast: true
          type: weather-forecast
          entity: weather.ksea_daynight
        - type: "custom:sun-card"
          entity: sun.sun
      - type: vertical-stack
        cards:
        - type: picture-elements
          entity: camera.mealie_todays_meal_image
          camera_image: camera.mealie_todays_meal_image
          title: Tonight's Dinner
          elements:
          - type: 'custom:config-template-card'
            variables:
              URL: states['sensor.mealie_todays_meal'].attributes['orgUrl']
            entities:
            - sensor.mealie_todays_meal
            style: 
              left: 50%
              bottom: 5%
              width: 100%
              background-color: var(--primary-background-color)
              opacity: 0.8
              text-align: right
              font-size: 2vw
              padding-bottom: 5px
            element:
              type: state-label
              entity: sensor.mealie_todays_meal
              attribute: name
              tap_action:
                action: url
                url_path: "${URL}"
        - type: media-control
          entity: media_player.sound_system
        - type: media-control
          entity: media_player.basement_tv
  - path: commute
    title: Commute
    cards:
    - type: entities
      title: "Transit Schedule"
      entities:
      - type: attribute
        entity: sensor.3_1_w_centralmagnolia
        name: "31 Central Magnolia"
        attribute: "Due in"
        suffix: min
      - type: attribute
        entity: sensor.3_2_w_seattlecenter
        name: "32 Seattle Center"
        attribute: "Due in"
        suffix: min
      - type: divider
      - type: attribute
        entity: sensor.3_1_e_seattlechildrens
        name: "31 Seattle Children's"
        attribute: "Due in"
        suffix: min
      - type: attribute
        entity: sensor.3_2_e_seattlechildrens
        name: "32 Seattle Children's"
        attribute: "Due in"
        suffix: min
      - type: divider
      - type: attribute
        entity: sensor.link_anglelake
        name: "Link Angle Lake"
        attribute: "Due in"
        suffix: min
      - type: attribute
        entity: sensor.link_northgate
        name: "Link Northgate"
        attribute: "Due in"
        suffix: min
    - type: map
      entities:
      - zone.home
      - sensor.3_1_w_centralmagnolia
      - sensor.3_2_w_seattlecenter
      - sensor.3_1_e_seattlechildrens
      - sensor.3_2_e_seattlechildrens
      - sensor.link_anglelake
      - sensor.link_northgate
      default_zoom: 20

