title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: vertical-stack
        cards:
        - show_current: true
          show_forecast: true
          type: weather-forecast
          entity: weather.forecast_home
          secondary_info_attribute: precipitation
        - show_current: false
          show_forecast: true
          type: weather-forecast
          entity: weather.forecast_home_hourly
          secondary_info_attribute: precipitation
        - type: "custom:sun-card"
          entity: sun.sun
      - type: vertical-stack
        cards:
        - type: picture-elements
          entity: camera.mealie_todays_meal_image
          camera_image: camera.mealie_todays_meal_image
          title: Tonight's Dinner
          elements:
          - type: 'custom:config-template-card'
            variables:
              URL: states['sensor.mealie_todays_meal'].attributes['orgUrl']
            entities:
            - sensor.mealie_todays_meal
            element:
              type: state-label
              entity: sensor.mealie_todays_meal
              attribute: name
              style: 
                left: 50%
                bottom: -10%
                width: 100%
                background-color: var(--primary-background-color)
                opacity: 0.8
                text-align: right
                font-size: medium
              tap_action:
                action: ${URL == "" ? none : url}
                url_path: "${URL}"
        - type: media-control
          entity: media_player.sound_system


